# Generated by Django 2.1.1 on 2018-09-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0, verbose_name='Значение')),
                ('timestamp', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'ordering': ['timestamp'],
                'verbose_name_plural': 'Значение сенсора',
                'verbose_name': 'Значение сенсора',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сенсора')),
                ('description', models.TextField(verbose_name='Описание отображаемой информации')),
            ],
            options={
                'verbose_name_plural': 'Сенсоры',
                'verbose_name': 'Сенсор',
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='sensor',
            field=models.ForeignKey(blank=True, default=1, help_text='Источник информации', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='rest.Sensor', verbose_name='Сенсор/Счётчик/Датчик'),
        ),
    ]
