# Generated by Django 2.1.1 on 2018-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя сенсора'),
        ),
    ]
