# Generated by Django 2.1.1 on 2018-09-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180924_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название комнаты')),
                ('description', models.TextField(verbose_name='Описание комнаты, что там находится, итп')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='room',
            field=models.ForeignKey(default=1, help_text='Идентификатор комнаты в которой находится датчик, и откуда пришло измерение', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rest.Room', verbose_name='Комната'),
        ),
    ]
